name: Build and test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build with Node
        run: |
          npm ci
          npm run build

      - name: Test
        run: npm test

      - name: Build with Docker
        uses: docker/build-push-action@v3.2.0
        with:
          push: false
          target: production
