name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Type of version to release"
        type: choice
        required: true
        options:
          - major
          - minor
          - patch

concurrency: release-${{ inputs.version }}

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Release
        id: release
        shell: bash
        run: |
          npm ci
          npm run release -- ${{ inputs.version }}
          JSON=$(cat version.json)
          VERSION=fromJSON($JSON).version
          echo version=${VERSION} >>$GITHUB_OUTPUT

      - run: echo ${{ steps.release.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: tiagoboeing/bull-board:${{ env.GENERATED_VERSION }}
          target: production
