name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Type of version to release"
        type: choice
        required: true
        options:
          - major
          - minor
          - patch

concurrency: release-${{ inputs.version }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        working-directory: ${{ github.workspace }}
        with:
          node-version: 16
      - run: npm ci
      - run: release-it --only-version --dry-run --${{ inputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: tiagoboeing/bull-board:${{ env.BRANCH_NAME }}-SNAPSHOT
          target: production
