name: Build and push snapshots

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: tiagoboeing/bull-board:${{ github.ref_name }}-SNAPSHOT
          target: production
